### ISSUE TITLE
Missing adlib_v3 module?

### ISSUE THREAD

**Issue by buddhawilliams** [bfidatadigipres/dpx_encoding#2]
I have investigated rawcooked, and found that it would work for us, then a colleague saw an iPres presentation of yours so directed me to this code. 
Note that I am a PHP dev and Linux admin, and any Python experience is 'follow the bouncing ball', so perhaps I have done something wrong here, but when I run dagster on my dev box, I get: 
`
dagster.code_server - ERROR - dagster._core.errors.DagsterImportError: Encountered ImportError: "No module named 'adlib_v3'" while importing module bfi_dagster_project. Local modules were resolved using the working directory "/data/bfi/venv/dpx_encoding". If another working directory should be used, please explicitly specify the appropriate path using the "-d" or "--working-directory" for CLI based targets or the `working_directory` configuration option for workspace targets.
`

From my limited knowledge of Python, it appears that the adlib_v3 module is supposed to be included in the code base here, but when I do a grep on all the code, I only find uses of the module, no definitions, and no files called `adlib` or similar.

I have created a venv and have all the prerequisites installed (although ffmpeg is v6.1.1 - I figured I would be able to at least get the environment running before upgrading that).
I am running on Ubuntu 24.04, python3.12.3/pip24.0, and I have installed the requirements.txt file with pip. 

Looking at the code, I noticed that the path was being set to the environment variable CODE so I have set that to a variety of places in the tree, but since there doesn't seem to be a definition anywhere, that felt pointless, but tried it anyway! also have set DAGSTER_HOME, but no other env variables are currently set (apart from those already set).
```
CODE=/data/bfi/venv/dpx_encoding/bfi_dagster_project/
DAGSTER_HOME=/data/bfi/venv/dpx_encoding/bfi_dagster_project
```

Happy to provide more info if needed. 
Cheers
Paul

**Comment by digitensions** [comment]
Hey Paul,

Thanks so much for your interest! Apologies you sailed in at a moment when I've just made major revisions to the code - we're testing Dagster ourselves at the moment. I pushed some new README data last thing before leave, with expectation of fixing today!

Adlib_v3 is in BFI_scripts repository. It's the library that pushes/pulls data to our Axiell database. I'd guess you won't have anything that maps to that in your workflow, and would advise removing any code/imports for this library. That should get things running for you pretty fast!

I'll add notes to this effect later today. The CODE variable is pointing to BFI_scripts on our servers.

Thanks again and happy to chat more!

Joanna

**Comment by buddhawilliams** [comment]
Thanks Joanna, I had just discovered that BFI_Scripts repo and was about to amend my query here with that info. I am still getting errors, but it looks like unset variables, etc, so will go and have a play since it looks like it is basically working.
Paul

**Comment by digitensions** [comment]
Amazing! Let me know how you get on. Just to advise, I think the sensor __init__.py / retry python code isn't working yet. I need to get some database entries with RAWcookd failed to test this on then I'll make some revisions to these blocks of code.

Happy Dagstering, and amazing you got it nearly set up already.
